application: jmapsdemos
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: media/css
- url: /images
  static_dir: media/images
- url: /js
  static_dir: media/js
- url: /geocode
  script: geocode.py
- url: .*
  script: main.py
